apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  ports:
  - port: 2283
    targetPort: 3001
  selector:
    app: immich-server
  type: LoadBalancer
  loadBalancerIP: 172.16.23.30
