apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  ports:
  - port: 5000 # Assuming the ML service listens on port 5000; adjust if needed
    targetPort: 5000
  selector:
    app: immich-machine-learning
  type: ClusterIP
