apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:release
        volumeMounts:
        - name: model-cache-volume
          mountPath: /cache
        envFrom:
        - configMapRef:
            name: immich-config
      volumes:
      - name: model-cache-volume
        hostPath:
          path: /data-nfs/immich
