apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  # Add non-sensitive data here
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"

---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
type: Opaque
data:
  # Use base64 to encode sensitive values
  DB_PASSWORD: "cGFzc3dvcmQ="
