apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  # Add non-sensitive data here
  POSTGRES_USER: "immich"
  POSTGRES_DB: "immich"

---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
type: Opaque
data:
  # Use base64 to encode sensitive values
  DB_PASSWORD: "cGFzc3dvcmQ="
